services:
  graphhopper:
    image: israelhikingmap/graphhopper:latest
    ports:
      - "8989:8989"
    volumes:
      - ./graphhopper-data:/data
    environment:
      - JAVA_OPTS=-Xmx8g -Xms3g
    command: >
      --config /data/config.yml

      
    

#  rust-api:
#    build: ./core-api
#    ports:
#     - "3000:3000"
#    depends_on:
#      - graphhopper
#    volumes:
#      - ./core-api:/usr/src/core-api
#    environment:
#      - GRAPHHOPPER_URL=http://localhost:8989
#   restart: always