services:
  graphhopper:
    image: israelhikingmap/graphhopper:latest
    ports:
      - "8989:8989"
    volumes:
      - ./graphhopper-data:/data
    environment:
      - JAVA_OPTS=-Xmx4g -Xms1g
    command: >
      --port 8989
      --host 0.0.0.0
      --input /data/osm/ile-de-france-latest.osm.pbf
      
    

  rust-api:
    build: ./core-api
    ports:
      - "3000:3000"
    depends_on:
      - graphhopper
    environment:
      - GRAPHHOPPER_URL=http://localhost:8989
    restart: always