[package]
name = "core-api"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web server and routing
actix-web = "4.3.1"
actix-cors = "0.6.4"

futures = "0.3.31"
redis = { version = "0.23", features = ["tokio-comp", "connection-manager"] }
once_cell = "1.18.0"
tokio = { version = "1.28", features = ["full"] }

# Serialization/deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Logging
log = "0.4"
env_logger = "0.10"

# Config management
config = "0.13"
dotenv = "0.15"

# Geo utilities
geo-types = "0.7"
geo = "0.24"
geojson = "0.24"

# Error handling
thiserror = "1.0"
anyhow = "1.0"
chrono = { version = "0.4.40", features = ["serde"] }
reqwest = { version = "0.11", features = ["json"] }

# Spatial indexing and geometric operations
rstar = "0.11"
uuid = { version = "1.0", features = ["v4"] }
rand = "0.8"