graphhopper:
  datareader.file: /data/osm/ile-de-france-latest.osm.pbf  # https://download.geofabrik.de/europe/france/ile-de-france-latest.osm.pbf
  graph.location: /data/graphs
  gtfs.file: /data/gtfs/IDFM-gtfs.zip   # https://eu.ftp.opendatasoft.com/stif/GTFS/IDFM-gtfs.zip
  import.osm.ignored_highways: motorway,trunk
  profiles:
    - name: foot
      custom_model_files:
        - foot.json
    - name: pt
      custom_model: {"speed": [{ "if": "true", "limit_to": "foot_average_speed" }]}
  graph.encoded_values: foot_access, foot_average_speed, foot_priority, foot_road_access, hike_rating, mtb_rating, country, road_class

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0